seed: 424
use_wandb: false
input_data_dir: /qwarium/home/d.a.lanovenko/llm-detect-ai/datasets

model:
  backbone_path: ../models/r_detect_mix_v16/best  # Предобученная модель на ai-mix-v16
  max_length: 1024
  num_labels: 1
  
  tokenizer:
    padding_side: left
    truncation_side: left
    use_fast: true

  lora:
    target_modules:
      - q_proj
      - k_proj
    r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    modules_to_save:
      - classification_head

train_params:
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 2
  num_train_epochs: 2
  gradient_accumulation_steps: 8
  warmup_pct: 0.05
  eval_frequency: 150
  patience: 8
  save_trigger: 0.85

optimizer:
  name: AdamW8bit
  head_lr: 5e-7
  lr: 5e-6
  weight_decay: 1e-2
  max_grad_norm: 0.5

outputs:
  model_dir: /qwarium/home/d.a.lanovenko/models/r_detect_transfer

wandb:
  project: detect-ai-a1
  run_name: exp003-transfer-detect
  tags:
    - mistral
    - transfer
